Update makeproject to provide material to get started
git-svn-id: https://europa-pso.googlecode.com/svn/PLASMA/trunk@2119 23e1bc29-d954-0410-9766-47de34158ba0

diff --git a/makeproject b/makeproject
--- a/makeproject
+++ b/makeproject
@@ -4,6 +4,8 @@
 # with the name NAME.  it populates this directory with basic
 # project files that use PLASMA.
 #
+# See ./NDDL/test/project/* for source material
+#
 PLASMA=`dirname "$0"`
 if [ "$1" == "" ]
 then
@@ -13,6 +15,7 @@ then
   echo "Example: makeproject IDEA"
   exit -1
 fi
+
 NAME="$1"
 
 DIRECTORY="$PLASMA/../$NAME"
@@ -30,6 +33,7 @@ then
   exit -1
 fi
 echo "Adding Jamrules"
+
 touch $DIRECTORY/Jamrules
 echo "{"                                                     >> $DIRECTORY/Jamrules
 echo "  local SUBDIR = \$("$NAME") ;"                        >> $DIRECTORY/Jamrules
@@ -44,16 +48,83 @@ then
   echo "error: "$DIRECTORY"/Jamfile already exists"
   exit -1
 fi
+
 echo "Adding Jamfile"
-touch $DIRECTORY/Jamfile
-echo "SubDir "$NAME" ;"                                        >> $DIRECTORY/Jamfile
-echo ""                                                        >> $DIRECTORY/Jamfile
-echo "if ! \$("$NAME"_READY) {"                                >> $DIRECTORY/Jamfile
-echo ""                                                        >> $DIRECTORY/Jamfile
-echo "Echo No project rules defined yet. ;"                    >> $DIRECTORY/Jamfile
-echo "# Put your project rules here.  Usually you will put a"  >> $DIRECTORY/Jamfile
-echo "# SubInclude command here and create your modules, etc." >> $DIRECTORY/Jamfile
-echo "# in directories below this one.  See the Jamfile in"    >> $DIRECTORY/Jamfile
-echo "# the PLASMA directory for examples."                    >> $DIRECTORY/Jamfile
-echo ""                                                        >> $DIRECTORY/Jamfile
-echo "} # "$NAME"_READY"                                       >> $DIRECTORY/Jamfile
+echo "SubDir "$NAME" ;" >> $DIRECTORY/Jamfile
+echo "" >> $DIRECTORY/Jamfile
+echo "if ! \$("$NAME"_READY) {" >> $DIRECTORY/Jamfile
+echo " # Create a build target to run a problem" >> $DIRECTORY/Jamfile
+echo " RunProblem "$NAME" : "$NAME"-initial-state.nddl : "$NAME"-planner ;" >> $DIRECTORY/Jamfile
+echo "" >> $DIRECTORY/Jamfile
+echo " # Create a build target for the planner executable with the given model." >> $DIRECTORY/Jamfile
+echo " NddlMain "$NAME"-planner : "$NAME"-Main.cc : "$NAME"-model.nddl : NDDL : "$NAME"-planner ;" >> $DIRECTORY/Jamfile
+echo "} # "$NAME"_READY" >> $DIRECTORY/Jamfile
+
+
+if [ -e $DIRECTORY/$NAME-model.nddl ]
+then
+  echo "error: "$DIRECTORY"/"$NAME"-model.nddl already exists"
+  exit -1
+fi
+
+echo "Adding "$NAME"-model.nddl"
+echo "#include \"../PLASMA/NDDL/core/Plasma.nddl\"" >> $DIRECTORY/$NAME-model.nddl
+echo "#include \"../PLASMA/NDDL/core/PlannerConfig.nddl\"" >> $DIRECTORY/$NAME-model.nddl
+echo "" >> $DIRECTORY/$NAME-model.nddl
+echo "/**" >> $DIRECTORY/$NAME-model.nddl
+echo " * @brief Place holder class with a single predicate" >> $DIRECTORY/$NAME-model.nddl
+echo " */" >> $DIRECTORY/$NAME-model.nddl
+echo "class YourObject extends Timeline {" >> $DIRECTORY/$NAME-model.nddl
+echo " predicate helloWorld{} /*!< Predicate with no arguments */" >> $DIRECTORY/$NAME-model.nddl
+echo "}" >> $DIRECTORY/$NAME-model.nddl
+echo "" >> $DIRECTORY/$NAME-model.nddl
+echo "/**" >> $DIRECTORY/$NAME-model.nddl
+echo " * @brief A simple rule to force a repeated cycle" >> $DIRECTORY/$NAME-model.nddl
+echo " */" >> $DIRECTORY/$NAME-model.nddl
+echo "YourObject::helloWorld{" >> $DIRECTORY/$NAME-model.nddl
+echo " eq(duration, 10);" >> $DIRECTORY/$NAME-model.nddl
+echo " meets (object.helloWorld);" >> $DIRECTORY/$NAME-model.nddl
+echo " met_by(object.helloWorld);" >> $DIRECTORY/$NAME-model.nddl
+echo "}" >> $DIRECTORY/$NAME-model.nddl
+
+
+if [ -e $DIRECTORY/$NAME-initial-state.nddl ]
+then
+  echo "error: "$DIRECTORY"/"$NAME"-initial-state.nddl already exists"
+  exit -1
+fi
+echo "Adding "$NAME"-initial-state.nddl"
+echo "#include \""$NAME"-model.nddl\"" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// Create a planner configuration instance in PLASMA." >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// Horizon Start, Horizon End, MaxPlannerSteps" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "PlannerConfig plannerConfiguration = new PlannerConfig(0, 1000, 500);" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// Sample object" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "YourObject object = new YourObject();" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// Close the the PLASMA Database - no more objects can be created." >> $DIRECTORY/$NAME-initial-state.nddl
+echo "close();" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// Now place your goals here." >> $DIRECTORY/$NAME-initial-state.nddl
+echo "goal(YourObject.helloWorld initialToken);" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "initialToken.start.specify(0); // Starts at beginning of the horizon" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "" >> $DIRECTORY/$NAME-initial-state.nddl
+echo "// The planner should take it form here!" >> $DIRECTORY/$NAME-initial-state.nddl
+
+if [ -e $DIRECTORY/"$NAME"-Main.cc ]
+then
+  echo "error: "$DIRECTORY"/"$NAME"-Main.cc already exists"
+  exit -1
+fi
+echo "Adding "$NAME"-Main.cc"
+cp ./NDDL/test/project/Main.cc $DIRECTORY/$NAME-Main.cc
+
+
+if [ -e $DIRECTORY/ppw-config ]
+then
+  echo "error: "$DIRECTORY"/ppw-config already exists"
+  exit -1
+fi
+echo "Adding ppw-config"
+cp ./NDDL/test/project/ppw-config $DIRECTORY
