Skip OPTIMIZE=3 for now; a single module test executable presently takes the compiler more than two hours. Email status from within the script for each variant instead of relying on cron to send email.
git-svn-id: https://europa-pso.googlecode.com/svn/PLASMA/trunk@1034 23e1bc29-d954-0410-9766-47de34158ba0

diff --git a/System/test/autobuild b/System/test/autobuild
--- a/System/test/autobuild
+++ b/System/test/autobuild
@@ -1,7 +1,10 @@
 #!/bin/sh
-# $Id: autobuild,v 1.7 2002-11-05 19:33:46 wedgingt Exp $
+# $Id: autobuild,v 1.8 2002-11-06 00:58:17 wedgingt Exp $
 #
 # Automatically build some variants of the Europa planner system
+
+# Address to mail exit status messages to
+email=checkins@postdoc.arc.nasa.gov
 
 # Don't try to use X11 (mostly to prevent Purify from doing so)
 DISPLAY=
@@ -45,7 +48,8 @@ mkdir resubmit || exit 1
 
 rmdir restart resubmit || exit 2
 
-subdirs='cvs opt fast optFast'
+#subdirs='cvs opt fast optFast'
+subdirs='cvs fast'
 
 # Primary compilation loop
 for dir in $subdirs
@@ -77,18 +81,18 @@ do
 
     if test "$status" != 0
     then
-	mkdir working/cvs.co.failed
-	exit "$status"
+        mkdir working/cvs.co.failed
+        exit "$status"
     fi
 
     if test -f ../make.options
     then
-	# Add to commonMakeOptions.imake
-	head -2 commonMakeOptions.imake > cMO.new
-	cat ../make.options >> cMO.new
-	echo '' >> cMO.new
-	tail +3 commonMakeOptions.imake >> cMO.new
-	mv -f cMO.new commonMakeOptions.imake
+        # Add to commonMakeOptions.imake
+        head -2 commonMakeOptions.imake > cMO.new
+        cat ../make.options >> cMO.new
+        echo '' >> cMO.new
+        tail +3 commonMakeOptions.imake >> cMO.new
+        mv -f cMO.new commonMakeOptions.imake
     fi
 
     test -d "$startdir"/working || exit 2
@@ -98,7 +102,14 @@ do
     status=$?
     echo '"make tests" in '"`pwd`"' exited '"$status"
 
-    test $status = 0 || mkdir working/failed
+    if test $status = 0
+    then
+        /usr/ucb/Mail -s 'Autobuild in '"`pwd`"' succeeded' "$email" < ../make.options
+    else
+        ( cat ../make.options; echo ''; tail -40 make.tests) | \
+            /usr/ucb/Mail -s 'Autobuild in '"`pwd`"' failed; exited '"$status" "$email"
+        mkdir working/failed
+    fi
 
     rmdir working || exit 1
 
